version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 15

    groups:
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      eslint:
        patterns:
          - "eslint"
          - "@eslint/js"
      typescript-eslint:
        patterns:
          - "typescript-eslint"
          - "@typescript-eslint/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 15
