name: CI

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run commitlint check
        if: always()
        run: npx commitlint -f ${{ github.event.pull_request.base.sha }}

      - name: Run ESLint check
        if: always()
        run: npm run lint

      - name: Run Prettier check
        if: always()
        run: npm run format

      - name: Check types
        if: always()
        run: npm run typecheck

      - name: Check dead code
        if: always()
        run: npm run knip
