name: Integration Tests

on:
  pull_request:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  vitest-integration:
    name: Vitest Integration Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20, 22, 24]
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install create-next-app globally
        run: npm install -g create-next-app@latest

      - name: Install dependencies
        run: npm ci

      - name: Build the package
        run: npm run build

      - name: Run Vitest integration tests
        run: npm test
        env:
          NODE_VERSION: ${{ matrix.node-version }}
