name: Publish Package Preview
on:
  push:
    branches:
      - "**"
    tags:
      - "!**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install
        uses: ./.github/composite-actions/install

      - run: npx pkg-pr-new publish
