name: Publish

on:
  push:
    branches:
      - main
      - next

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.COOLIFY_APP_ID }}
          private-key: ${{ secrets.COOLIFY_PRIVATE_KEY }}

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Publish
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
